name: graphcft

data:
  data_root: data/PROTEINS
  dataset: PROTEINS
  batch_size: 32
  num_workers: 1
  seed: 46

# model for data
model:
  _target_: models.graphcft.BaseGraph
  in_feat: 3
  hidden_dim: 32
  num_class: 2
  aggr: 'gat'
  layers: 2

# optimizer for training task model
optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005

# lr scheduler for training task optimizer
lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [10, 20]
  gamma: 0.2

epoch: 50
save_num_model: 50
train_layer: 'all'
# train_layer: [ 'conv_layers.1.att_src', 'conv_layers.1.att_dst', 'conv_layers.1.bias', 'conv_layers.1.lin.weight', 'out.weight', 'out.bias']

# parameter data root
param:
  data_root: param_data/PROTEINS/data.pt
  k: 50
  num_workers: 4
