tasks:
  - citeseer
  - cora
  - PubMed
param:
  data_root: param_data/Cora/data_transfer.pt
  k: 50
  token_length: 128
  num_workers: 4
  num_encoder_latents: 16
  dim_ae: 16
  tf: False
#  train_list: ['Cora1', 'Cora3']
  test_list: ['CiteSeer', 'Cora', 'PubMed']
#  test_list: ['Cora1', 'Cora3', 'Cora2']
  test_dim: [32]


#[17321,119922, 47317]
#119782